// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0flOEcdyyBhEV8mm-JjhcKYw9Gb5FoIw',
    appId: '1:769537265304:web:6a5719c8fa1bca54684aed',
    messagingSenderId: '769537265304',
    projectId: 'kascustomer',
    authDomain: 'kascustomer.firebaseapp.com',
    storageBucket: 'kascustomer.firebasestorage.app',
    measurementId: 'G-58DEZ8YYNZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAjaJ3zul6pnQmUZDwYxAasZ0tTb4m7D4',
    appId: '1:769537265304:android:e25db359c3ebb3d0684aed',
    messagingSenderId: '769537265304',
    projectId: 'kascustomer',
    storageBucket: 'kascustomer.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEPYq6z5p085WCE0tp7Fq6nMOUzhqrtcQ',
    appId: '1:769537265304:ios:5de4a0e89a54abfc684aed',
    messagingSenderId: '769537265304',
    projectId: 'kascustomer',
    storageBucket: 'kascustomer.firebasestorage.app',
    iosBundleId: 'com.kascustomer.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEPYq6z5p085WCE0tp7Fq6nMOUzhqrtcQ',
    appId: '1:769537265304:ios:e290b64903a3888a684aed',
    messagingSenderId: '769537265304',
    projectId: 'kascustomer',
    storageBucket: 'kascustomer.firebasestorage.app',
    iosBundleId: 'com.example.kasnew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0flOEcdyyBhEV8mm-JjhcKYw9Gb5FoIw',
    appId: '1:769537265304:web:1e35ecde28fd4f14684aed',
    messagingSenderId: '769537265304',
    projectId: 'kascustomer',
    authDomain: 'kascustomer.firebaseapp.com',
    storageBucket: 'kascustomer.firebasestorage.app',
    measurementId: 'G-876Z0YFGPH',
  );

}